#spring:
#  application:
#    name: car-management-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/car_info_db
#    password: dumith
#    username: dumith
#    initialization-mode: always
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
server:  port: 8100
eureka:
  client:
    enabled: true    service-url:      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}  