INSERT INTO CAR(REG_NUM,BRAND,MODEL) VALUES('58-2156','TOYOTA','COROLLA');
INSERT INTO CAR(REG_NUM,BRAND,MODEL) VALUES('ABF-5465','NISSAN','TINA');
INSERT INTO CAR(REG_NUM,BRAND,MODEL) VALUES('KIP-6395','FORD','MUSTANG');
INSERT INTO CAR(REG_NUM,BRAND,MODEL) VALUES('AEC-8832','TOYOTA','CAMRY');
INSERT INTO CAR(REG_NUM,BRAND,MODEL) VALUES('31-4436','HONDA','E1');